# Generated by Django 5.1.1 on 2024-09-17 05:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_items_delete_moodentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
